# Generated by Django 5.2.1 on 2025-05-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='colled_id',
            new_name='college_id',
        ),
    ]
