# Generated by Django 5.2.1 on 2025-05-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('department', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='colled_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
