# Generated by Django 5.2.1 on 2025-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_colled_id_customuser_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('Phd', 'Phd'), ('Asis.Prof', 'Asis.Prof'), ('Hod', 'Hod'), ('B.tech Student', 'B.tech Student')], null=True),
        ),
    ]
