# Generated by Django 5.2.1 on 2025-05-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('department', '0001_initial'),
        ('user', '0003_alter_customuser_colled_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='colled_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.college'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
