# Generated by Django 5.2.1 on 2025-05-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_delete_deparment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='college',
            new_name='college_id',
        ),
    ]
