# Generated by Django 5.2.1 on 2025-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
