# Generated by Django 5.2.1 on 2025-05-13 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_designation', models.CharField(choices=[('HOD', 'Head of Department'), ('PhD', 'PhD Holder'), ('Professor', 'Professor'), ('Asst. Professor', 'Assistant Professor')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to='department.department')),
            ],
        ),
    ]
