# Generated by Django 5.2.1 on 2025-05-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='id_department',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='id',
            new_name='staff_id',
        ),
    ]
