# Generated by Django 5.2.1 on 2025-05-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_department_staff_id_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
